/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleRouteImport } from './routes/style'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as ClosetRouteImport } from './routes/closet'
import { Route as IndexRouteImport } from './routes/index'

const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetRoute = ClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gifts': typeof GiftsRoute
  '/shop': typeof ShopRoute
  '/style': typeof StyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gifts': typeof GiftsRoute
  '/shop': typeof ShopRoute
  '/style': typeof StyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gifts': typeof GiftsRoute
  '/shop': typeof ShopRoute
  '/style': typeof StyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/closet' | '/gifts' | '/shop' | '/style'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/closet' | '/gifts' | '/shop' | '/style'
  id: '__root__' | '/' | '/closet' | '/gifts' | '/shop' | '/style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosetRoute: typeof ClosetRoute
  GiftsRoute: typeof GiftsRoute
  ShopRoute: typeof ShopRoute
  StyleRoute: typeof StyleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet': {
      id: '/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof ClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosetRoute: ClosetRoute,
  GiftsRoute: GiftsRoute,
  ShopRoute: ShopRoute,
  StyleRoute: StyleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
